### ISSUE TITLE
Running time is so slow and got error when plot graph

### ISSUE THREAD

**Issue by linlih** [trevorcampbell/pseudocoresets-experiments#2]
I wonder what environment that the code used.
I got a lot of error in Ubuntu 16.04. 
Such as :
RuntimeError: Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'.
I try to fix this problem, but it still won't work out.

Only to export a png result need to use web browser, just output a image file in current directroy will be more easy

**Comment by linlih** [comment]
I trying to fix this problem, but when export png file, it occurs other problem

```bash
/home/linlh/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
WARNING:bokeh.io.export:The webdriver raised a TimeoutException while waiting for a 'bokeh:idle' event to signify that the layout has rendered. Something may have gone wrong.
WARNING:bokeh.io.export:There were browser warnings and/or errors that may have affected your export
WARNING:bokeh.io.export:javascript 30:13 Uncaught ReferenceError: power_digits is not defined
Traceback (most recent call last):
  File "plot_kl.py", line 56, in <module>
    export_png(fig, filename=os.path.join(fldr_figs, "KLDvsCstSize.png"), height=500, width=1000)
  File "/home/linlh/.local/lib/python3.6/site-packages/bokeh/io/export.py", line 104, in export_png
    raise ValueError("unable to save an empty image")
ValueError: unable to save an empty image
```
